swagger: '2.0'
info:
  title: 'Game Curator API'
  description: 'Learning project API to retrieve and manipulate game review data.'
  version: 'v1'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
  contact:
    name: IS Data Architecture Team
    url: https://is.oregonstate.edu/data-architecture
    email: isdataarchitecture@oregonstate.edu
#host: 'test.swagger.io'
paths:
  /game:
    get:
      summary: 'Find game by ID'
      responses:
        200:
          description: 'Successful response'
    post:
      summary: 'Add a new game'
      responses:
        201:
          description: 'Successfully added a game'
        405:
          description: 'Invalid input'
definitions:
  Game:
    type: "object"
    properties:
      id:
        type: 'integer'
        format: 'int64'
